import React, { useState, useEffect } from 'react';
import { X, Sparkles, Loader2 } from 'lucide-react';
import { api } from '../services/api';

interface AIPanelProps {
  threadId: string;
  onClose: () => void;
}

export const AIPanel: React.FC<AIPanelProps> = ({ threadId, onClose }) => {
  const [loading, setLoading] = useState(true);
  const [analysis, setAnalysis] = useState<string | null>(null);

  useEffect(() => {
    const runAnalysis = async () => {
      try {
        const result = await api.analyzeThread(threadId, true);
        setAnalysis(result.analysis);
      } catch (e) {
        setAnalysis("Failed to generate analysis. Please check your KIE API settings.");
      } finally {
        setLoading(false);
      }
    };
    runAnalysis();
  }, [threadId]);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4">
      <div className="bg-white w-full max-w-lg rounded-2xl shadow-2xl border border-slate-200 overflow-hidden flex flex-col max-h-[80vh]">
        <div className="p-4 border-b border-slate-100 flex justify-between items-center bg-gradient-to-r from-indigo-50 to-white">
          <div className="flex items-center gap-2 text-indigo-700">
            <Sparkles className="w-5 h-5" />
            <h3 className="font-bold">AI Insight</h3>
          </div>
          <button onClick={onClose} className="p-1 hover:bg-slate-100 rounded-full text-slate-400 hover:text-slate-600 transition-colors">
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-6 overflow-y-auto min-h-[200px]">
          {loading ? (
            <div className="flex flex-col items-center justify-center h-40 gap-3 text-slate-400">
              <Loader2 className="w-8 h-8 animate-spin text-indigo-500" />
              <p className="text-sm">Analyzing conversation history...</p>
            </div>
          ) : (
            <div className="prose prose-sm prose-slate max-w-none">
              <div className="whitespace-pre-wrap text-slate-700 leading-relaxed">
                {analysis}
              </div>
            </div>
          )}
        </div>

        <div className="p-4 bg-slate-50 border-t border-slate-100 text-xs text-slate-400 text-center">
          Analysis generated by KIE Gemini 3 Pro. Verify important details independently.
        </div>
      </div>
    </div>
  );
};
